# Generated by Django 5.1.1 on 2024-09-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codestar', '0004_alter_submission_unique_together_and_more'),
    ]

    operations = [
    ]
