# Generated by Django 5.1.1 on 2024-09-15 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestar', '0006_round_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='question',
            name='round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='codestar.round'),
            preserve_default=False,
        ),
    ]
