# Generated by Django 5.1.1 on 2024-09-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestar', '0008_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
