# Generated by Django 5.1.1 on 2024-09-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestar', '0009_round_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='expected_output',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='hidden_input',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='execution_time',
            field=models.FloatField(default=0.0),
        ),
    ]
