# Generated by Django 5.1.1 on 2024-09-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestar', '0010_question_expected_output_question_hidden_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='execution_time',
            field=models.FloatField(default=0.0),
        ),
    ]
