# Generated by Django 5.1.1 on 2024-09-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestar', '0011_alter_submission_execution_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='expected_output',
        ),
        migrations.RemoveField(
            model_name='question',
            name='hidden_input',
        ),
        migrations.AddField(
            model_name='question',
            name='expected_outputs',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='question',
            name='hidden_inputs',
            field=models.TextField(default='[]'),
        ),
    ]
