# Generated by Django 5.1.1 on 2024-09-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestar', '0012_remove_question_expected_output_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='expected_outputs',
        ),
        migrations.RemoveField(
            model_name='question',
            name='hidden_inputs',
        ),
        migrations.AddField(
            model_name='question',
            name='expected_output',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='hidden_input',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
