# Generated by Django 5.1.1 on 2024-09-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codestar', '0013_remove_question_expected_outputs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='expected_output',
        ),
        migrations.RemoveField(
            model_name='question',
            name='hidden_input',
        ),
    ]
