# Generated by Django 5.1.1 on 2024-09-16 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestar', '0014_remove_question_expected_output_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_time', models.FloatField(help_text='Minimum execution time in seconds')),
                ('max_time', models.FloatField(help_text='Maximum execution time in seconds')),
                ('score', models.IntegerField(help_text='Score awarded for this time range')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codestar.round')),
            ],
            options={
                'ordering': ['round', 'min_time'],
            },
        ),
    ]
