# Generated by Django 5.1.1 on 2024-09-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestar', '0016_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='timer',
            field=models.IntegerField(default=0, help_text='Timer in seconds for this round'),
        ),
    ]
