# Generated by Django 5.1.1 on 2024-09-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codestar', '0017_round_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='timer',
        ),
    ]
