# Generated by Django 5.1.1 on 2024-09-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestar', '0018_remove_round_timer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scoringrule',
            options={'ordering': ['round']},
        ),
        migrations.RemoveField(
            model_name='scoringrule',
            name='max_time',
        ),
        migrations.RemoveField(
            model_name='scoringrule',
            name='min_time',
        ),
        migrations.AddField(
            model_name='round',
            name='timer_duration',
            field=models.IntegerField(default=3600),
        ),
        migrations.AlterField(
            model_name='round',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scoringrule',
            name='score',
            field=models.IntegerField(help_text='Score awarded for correct answer'),
        ),
    ]
