# Generated by Django 5.1.1 on 2024-09-28 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestar', '0019_alter_round_options_alter_scoringrule_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='timer_duration',
            field=models.IntegerField(default=3600, help_text='Timer duration in seconds'),
        ),
        migrations.CreateModel(
            name='RoundCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codestar.round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'round')},
            },
        ),
        migrations.AddField(
            model_name='round',
            name='completed_by',
            field=models.ManyToManyField(related_name='completed_rounds', through='codestar.RoundCompletion', to=settings.AUTH_USER_MODEL),
        ),
    ]
