# Generated by Django 5.1.1 on 2024-09-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codestar', '0020_alter_round_timer_duration_roundcompletion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='completed_by',
        ),
        migrations.AlterField(
            model_name='round',
            name='timer_duration',
            field=models.IntegerField(default=3600),
        ),
        migrations.DeleteModel(
            name='RoundCompletion',
        ),
    ]
